### ISSUE TITLE
iOS websocket transport example

### ISSUE THREAD

**Issue by whyoleg** [rsocket/rsocket-kotlin#111]
For now, [ktor](ktor.io) doesn't support websockets on Native, so no support for iOS.
It would be good, to at least create an example transport implementation for that.
For inspiration: [example of iOS websockets written in kotlin](https://kotlinlang.org/docs/mobile/connect-to-platform-specific-apis.html#example-send-and-receive-messages-from-a-websocket)

**Comment by olme04** [comment]
From ktor 2.0, WebSockets are supported on native via Darwin and CIO client engines.
rsocket-kotlin version compatible with ktor 2.0 will be released soon, so issue can be closed after it

**Comment by whyoleg** [comment]
ktor 2.0 supports websockets on CIO and Darwin engines for iOS.
So rsocket-kotlin supports it out of the box starting from 0.15.4
