### ISSUE TITLE
incompatibilty with newer coroutines

### ISSUE THREAD

**Issue by NikkyAI** [rsocket/rsocket-kotlin#124]
when running with coroutines `1.3.9` or newer rsockets wil lcrash with a NoSuchMethodError

```
void kotlinx.coroutines.flow.internal.ChannelFlow.<init>(kotlin.coroutines.CoroutineContext, int)'
java.lang.NoSuchMethodError: 'void kotlinx.coroutines.flow.internal.ChannelFlow.<init>(kotlin.coroutines.CoroutineContext, int)'
```

## Steps to Reproduce

`build.gradle.kts`
```kotlin
dependencies {
    api("org.jetbrains.kotlinx:kotlinx-serialization-protobuf:1.0.1")
    api("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.2")

    api("io.ktor:ktor-client-cio:1.4.2")

    api("io.rsocket.kotlin:rsocket-core:0.11.5")
    api("io.rsocket.kotlin:rsocket-transport-ktor-client::0.11.5")
}
```

```
fun RSocket(protobuf: ProtoBuf, events: Flow<Event>) {
    requestChannel(
        payloads = events.map { event ->
            protobuf.encodeToPayload("track", Event.serializer(), event)
        }
    )
}
```

exception throws on call of `requestChannel`

## Possible Solution

`ChannelFlow::init` has 3 arguments now, currently `onBufferOverflow: BufferOverflow` is not passed

updating to a slightly newer version of coroutines would probably also help

## Your Environment

* RSocket version(s) used: 0.11.5
* Other relevant libraries versions: `kotlinx.coroutines 1.4.2`
* Platform (eg. JVM version (`javar -version`) or Node version (`node --version`)): java 14

**Comment by whyoleg** [comment]
Hey, it's not an issue now in master (0.12.0). Fixed by removal of usage of that internal API.
For now, 0.11.5 should be used with coroutines 1.3.9.

**Comment by NikkyAI** [comment]
i tried 1.3.9 too, but it seems to require exactly `1.3.9-native-mt-2`

**Comment by NikkyAI** [comment]
sadly i cannot downgrade my coroutines version because other depedencies need `1.4.1` minimum

**Comment by NikkyAI** [comment]
is 0.12.0 available in the bintray ?
alternatively is there a readme for how to build and publish to mavenLocal ? i seem to be running into errors there

**Comment by whyoleg** [comment]
0.12.0 is now in development, only snapshots are available.
Publish to mavenLocal should work without any configuration. But what targets do you need?

**Comment by NikkyAI** [comment]
seems like there is weird issues on windows where publishToMavenLocal requires the native binaries to be built beforehand but files were not found, since i only need jvm and js currently i could just run those tasks seperately and it worked

**Comment by whyoleg** [comment]
[0.12.0](https://github.com/rsocket/rsocket-kotlin/releases/tag/0.12.0) has just released.

**Comment by NikkyAI** [comment]
`requestChannel` seems to have a initialPayload parameter now.. is that just the first payload or does it have some kind of oeffect on the rest of the payloads ?

**Comment by whyoleg** [comment]
it's just a first payload. F.e. where you will have some `routing` metadata or other info needed to initiate stream

**Comment by whyoleg** [comment]
Fixed in 0.12.0

**Comment by NikkyAI** [comment]
> it's just a first payload. F.e. where you will have some `routing` metadata or other info needed to initiate stream

just to clarify this.. when opening a channel only the first payload needs to to have routing metadata ?

**Comment by whyoleg** [comment]
it of course depends on server implementation, but yes.
As for `Routing Metadata` if to look on [protocol documentation](https://github.com/rsocket/rsocket/blob/master/Extensions/Routing.md#metadata-payload).
> This metadata type is intended to be used per stream, and not per connection nor individual payloads and as such it MUST only be used in frame types used to initiate interactions.
