### ISSUE TITLE
Intellij project build fails because of missing assemble target

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-kotlin#132]
## Expected Behavior

Clicking the project build icon in Intellij does a project build.

## Actual Behavior

```
Task 'assemble' not found in root project 'rsocket-kotlin'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

## Your Environment

OSX (MacBook Air M1)

**Comment by whyoleg** [comment]
it's intellij sync issue, not project issue. works ok on MBP with M1.

**Comment by yschimke** [comment]
Yep - works fine from the command line, so assuming it's an IDE bug.
