### ISSUE TITLE
Migrate from Jcenter to another repo

### ISSUE THREAD

**Issue by samuele794** [rsocket/rsocket-kotlin#160]
Jcenter is now deprecated (and read-only), needed migrate to another repository (example mavenCentral)
https://blog.gradle.org/jcenter-shutdown

**Comment by clayly** [comment]
Can we help somehow migrate from jcenter? Development moving away from it.

**Comment by olme04** [comment]
0.13.1 is published to Maven Central!

**Comment by altavir** [comment]
Superb. Could you please update the README to match this achievement?
