### ISSUE TITLE
Questions: iOS Websockets support

### ISSUE THREAD

**Issue by liskov** [rsocket/rsocket-kotlin#161]
Hi Guys, we want to use rsocket client with WebSockets underneath in our company on iOS and we wanted to ask you few questions.

we are seeing that iOS WebSockets not supported by this multiplatform library. we understand that it is probably because the ktor engine does still not support it

1. do you know if there any progress with this or near-future plans to implement websocket feature? or any other workaround?
2. do you know if there are any companies which use rsocket on iOS in production someway ?

we also saw new swift library, but it still too young and not production-ready and without few essential for us features like autoreconnect and routes.

3. do you know what will be the development phase of that library ? do you have any other suggestions for us ?

**Comment by olme04** [comment]
1. ktor will support websockets for iOS somewere after new MM will be stable
2. I don't :(
3. both rsocket-swift and rsocket-kotlin are in more or less in active development

IMO, rsocket-kotlin - now doesn't support secure tcp or ws for iOS, so it's not production ready for iOS yet. But websocket transport for iOS should be easy to implement, but at current moment I have no mac near...
as for rsocket-swift - I don't really know how far it's from production ready... may be @OlegDokuka can give some news here?

**Comment by whyoleg** [comment]
look at https://github.com/rsocket/rsocket-kotlin/issues/111#issuecomment-1101328670
