### ISSUE TITLE
Missing `all` and `sources` JAR versions in the latest snapshot release

### ISSUE THREAD

**Issue by mister11** [rsocket/rsocket-kotlin#162]
The latest snapshot release https://oss.jfrog.org/artifactory/oss-snapshot-local/io/rsocket/kotlin/rsocket-transport-ktor/0.13.0-SNAPSHOT/ (any module, not just `rsocket-transport-ktor`) does not contain `-all` and `-sources` JARs like the previous ones.

## Expected Behavior
The following configuration should work:

```
repositories {
    maven { url = uri("https://oss.jfrog.org/artifactory/oss-snapshot-local") }
}
...
implementation("io.rsocket.kotlin:rsocket-core:0.13.0-SNAPSHOT")
```

## Actual Behavior
The above-mentioned configuration does not work, but throws an error:
```
org.gradle.internal.resolve.ArtifactNotFoundException: Could not find rsocket-core-0.13.0-SNAPSHOT-all.jar (io.rsocket.kotlin:rsocket-core:0.13.0-SNAPSHOT:20210506.065912-11).
Searched in the following locations:
    https://oss.jfrog.org/artifactory/oss-snapshot-local/io/rsocket/kotlin/rsocket-core/0.13.0-SNAPSHOT/rsocket-core-0.13.0-20210506.065912-11-all.jar
```

## Steps to Reproduce
Use the above-mentioned configuration and reload Gradle project.

## Possible Solution
There are some changes in the root `build.gradle` around the latest release so maybe something broke there.

## Your Environment

* RSocket version(s) used: 0.13.0
* Java version: 15
* `uname -a`: `Linux tara 5.4.39-1-MANJARO #1 SMP PREEMPT Wed May 6 10:36:44 UTC 2020 x86_64 GNU/Linux`

**Comment by olme04** [comment]
As for now, artifactory for rsocket-kotlin is shutdown. Soon there will be 0.14.0 release, and snapshots on github packages.

**Comment by whyoleg** [comment]
Snapshots publication is migrated to Github Packages.
https://github.com/orgs/rsocket/packages?repo_name=rsocket-kotlin
