### ISSUE TITLE
Support Kotlin 1.5+

### ISSUE THREAD

**Issue by darvld** [rsocket/rsocket-kotlin#166]
Currently, in order to configure the Ktor client, some internal classes use an obsolete API for Duration handling, specifically, the KeepAlive constructor uses a syntax like `30.seconds`, which was removed from the Kotlin stdlib. This causes an immediate exception when configuring a client.

## Steps to Reproduce
Simply configure a Ktor client and add support for RSocket. It will immediately fail with an exception saying it can't find some method.

```kotlin
@Test
public void reproCase() {
  val client = HttpClient(CIO) {
          install(WebSockets.Feature)
          install(RSocketSupport)
  }
}
```

## Solution
Update to the new API, using `Duration.seconds()` and `Duration.minutes()` instead of `Int.seconds()`

**Comment by yschimke** [comment]
Blocked upstream with ktor issue and native builds https://github.com/rsocket/rsocket-kotlin/pull/168

**Comment by darvld** [comment]
Closing this as #168 adds support for Kotlin 1.5 (except on Native targets)
