### ISSUE TITLE
Can't catch exception when calling requestResponse in js

### ISSUE THREAD

**Issue by zt1106** [rsocket/rsocket-kotlin#186]
Using 0.13.1, Kotlin version is 1.5.30
<img width="673" alt="Screen Shot 2021-10-02 at 00 59 53" src="https://user-images.githubusercontent.com/20970607/135659673-9fc7c995-d934-43e7-a670-fc41ac7b2691.png">
.

**Comment by olme04** [comment]
Hey, try to catch `Throwable` not `Exception`. This should work

**Comment by zt1106** [comment]
Yes. Catch `Throwable` works. Too used to catch `Exception` in Java.
