### ISSUE TITLE
New Kotlin Multiplatform memory model

### ISSUE THREAD

**Issue by webfrea-k** [rsocket/rsocket-kotlin#192]
Hi guys, I see that release 0.14.0 is just around the corner. Do you plan to support new [KMM](https://github.com/JetBrains/kotlin/blob/master/kotlin-native/NEW_MM.md) soon? It looks like relatively simple update.
Coroutines version 1.6.0-RC or 1.6.0-RC2 and Ktor version 1.6.7 supports new MM by default (that's what I've gathered from the Youtrack and Github issues recently).

## Motivation
Lifted freezing restrictions on native
## Desired solution
As stated in the migration guide above

## Additional context
Side note: Is there 0.14.x Snapshot version available anywhere?

**Comment by olme04** [comment]
It should work now with https://github.com/JetBrains/kotlin/blob/master/kotlin-native/NEW_MM.md#unexpected-object-freezing (for atomicfu atomics). All other places should be covered by coroutines and ktor.
BTW, seems like only ktor 2.0.0 will support new MM explicitly.
After coroutines 1.6 will be released, I will check, what more we can do in `rsocket-kotlin` about new MM, at least setup tests for it.

**Comment by webfrea-k** [comment]
Ok great. I understood that the support is already there from [this comment](https://github.com/ktorio/ktor/pull/2693#issuecomment-970176692). 

Are there any snapshot builds available (0.14.0)? :)

**Comment by olme04** [comment]
> Ok great. I understood that the support is already there from [this comment](https://github.com/ktorio/ktor/pull/2693#issuecomment-970176692).

The same with rsocket-kotlin. On current moment, both stable versions of ktor and rsocket-kotlin supports new MM with flag to disable freezing.
With version 2.0.0 ktor, will support new MM even without this flag (as I see from [this branch](https://github.com/ktorio/ktor/tree/e5l/coroutines)).

> Are there any snapshot builds available (0.14.0)? :)
no :(, because our snapshot artifactory is shutdown. Soon there will be 0.14.0 release and support for snapshots via github packages

**Comment by olme04** [comment]
**Update:** looks like from ktor 2.0 (looking at [Drop old native memory model](https://github.com/ktorio/ktor/pull/2739)) ktor will support only new MM. So after ktor 2.0 release, we will also need to adapt rsocket-kotlin to new MM by default.

**Comment by olme04** [comment]
Ktor 2.0 released, and rsocket-kotlin is already migrated to it, and using new memory manager by default.
Stable release of rsocket-kotlin with support for new memory manager will be ready soon

**Comment by whyoleg** [comment]
Supported from 0.15.4
