### ISSUE TITLE
build-kotlinx-atomicfu is never used

### ISSUE THREAD

**Issue by jQrgen** [rsocket/rsocket-kotlin#233]
Why is there a `build-kotlinx-atomicfu` dependency in `gradle/libs.versions.toml` that is never used?

**Comment by whyoleg** [comment]
It's used in root buildscript:

https://github.com/rsocket/rsocket-kotlin/blob/a09a2b500e2e7b63c5837958eda8730f19b4cc00/build.gradle.kts#L26
