### ISSUE TITLE
Support Ktor 3.0.0

### ISSUE THREAD

**Issue by philip-segerfast** [rsocket/rsocket-kotlin#277]
Ktor 3.0.0 [was just released](https://github.com/ktorio/ktor/releases/tag/3.0.0) and it would be a great time to make rsocket-kotlin support it.

## Motivation
I need to use both RSocket and SSE in my client app but Ktor SSE client is only supported on Ktor 3.0.0 which rsocket-kotlin doesn't support yet, so an update would be great.

**Comment by whyoleg** [comment]
Hey!
Yeah, great news about ktor... Not so great about work required to migrate :)

I will merge active PRs and start working on migration to kotlinx-io and ktor 3.0 in coming weeks.
I'm pretty busy with other things right now, so I don't have expected release date.

**Comment by philip-segerfast** [comment]
Of course!
Thanks a lot for your response and your dedication to this library 🙏 It rocks!
Take all the time that is needed.
