### ISSUE TITLE
Update README examples

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-kotlin#43]
out of date currently e.g.

```
  .transport(OkhttpWebsocketClientTransport       // WebSockets transport
                  .create(protocol, host, port))
```

vs https://github.com/rsocket/rsocket-kotlin/blob/master/rsocket-transport-okhttp/src/main/kotlin/io/rsocket/transport/okhttp/client/OkhttpWebsocketClientTransport.kt

wants a Request

**Comment by mostroverkhov** [comment]
Yes, this needs to be updated - three params method was replaced by `create(url: HttpUrl)`

**Comment by yschimke** [comment]
@mostroverkhov BTW - I can probably help out with some of these.  At the moment, as I'm trying to use this I'm just logging things.

**Comment by whyoleg** [comment]
New readmed added in #100
