### ISSUE TITLE
Remove slf4j dependency

### ISSUE THREAD

**Issue by ration** [rsocket/rsocket-kotlin#56]
To use rsocket-kotlin on Android you also need to pull slf4j-api and slf4j-android. As far as I can tell the debug messages, which are few, are of rather limited use for end users. 

Thoughts?

I can PR this you you want..

**Comment by mostroverkhov** [comment]
Hello, I agree that slf4j can be moved from compile dependencies, but still prefer to have It on test configuration. Making some changes to project atm - so can introduce patch for this issue today

**Comment by mostroverkhov** [comment]
resolved by #58

**Comment by mostroverkhov** [comment]
current snapshot version changed to 0.9.6-SNAPSHOT

**Comment by ration** [comment]
wow that was fast, awesome!
Thanks!
