### ISSUE TITLE
RSocket infos

### ISSUE THREAD

**Issue by halimpuckjava** [rsocket/rsocket-kotlin#60]
hi

1.  what does mean payload ZERO_COPY ?
2.  when server is close (dispose() invoke) the acceptor keep listen for incoming message
3.  server can send request like client ?
4.  handler for :  client connect & disconnect, server start & dispose
5.  what effect to use onClose() ?

**Comment by mostroverkhov** [comment]
question relates to rsocket-java, and was answered on https://community.netifi.com/t/rsocket-features/194
